spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: hesuijin
    password : Hsj123456
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: mapper/oracle/**/*.xml,classpath:mapper/oracle/*.xml
