spring:
# 在RedisTemplate不需要设置配置类
  redis:
#    默认数据库
    database: 0
    host: 47.113.101.241
    port: 6379
    password: Hsj123456
    #连接Redis的超时时间 3000毫秒为3秒  仅有在使用时才会去连接
    timeout: 3000

    #    连接池
    lettuce:
      pool:
        #        连接池最大空闲链接  默认8
        max-idle: 8
        #       连接池最小空闲链接  默认0
        min-idle: 8
        #       连接池最大连接数（使用负值表示没有限制）  默认8
        max-active: 8
        #       更待可用链接最长时间 默认为-1 永不超时  1000毫秒 为1秒
        max-wait: 1000

#        连接池
    jedis:
      pool:
        #        连接池最大空闲链接  默认8
        max-idle: 8
        #       连接池最小空闲链接  默认0
        min-idle: 8
        #       连接池最大连接数（使用负值表示没有限制）  默认8
        max-active: 8
        #       更待可用链接最长时间 默认为-1 永不超时  1000毫秒 为1秒
        max-wait: 1000




# 如果需要配置redis哨兵 需要添加以下 redis.sentinel.nodes的配置
#spring:
#  redis:
#    sentinel:
#      master: mymaster
#      nodes:
#        - 111.xxx.xx.xxx:7001
#        - 112.xxx.xx.xxx:7002
#        - 113.xxx.xxx.xx:7003
#
#
# 如果需要配置redis集群 需要添加以下 redis.cluster.nodes的配置
#spring:
#   在RedisTemplate不需要设置配置类
#  redis:
#    cluster:
#     nodes:
#        - 111.xxx.xx.xxx:7001
#        - 112.xxx.xx.xxx:7002
#        - 113.xxx.xxx.xx:7003
